export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';